name: reviewdog
on: [pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: build custom analyzer
        run: |
          curl -o linters.tar.gz -L https://github.com/sapphi-red/possibleerrors/releases/download/v0.1.14/possibleerrors_golang-ci-lint-plugin_0.1.14_linux_64bit.tar.gz
          tar -xzf linters.tar.gz

          go get -u github.com/gostaticanalysis/vetgen
          vetgen init _vettool
          cd _vettool
          vetgen add //github.com/sapphi-red/possibleerrors/fordirection
          vetgen add //github.com/sapphi-red/possibleerrors/avoidaccesslen
          vetgen add //github.com/sapphi-red/possibleerrors/mutexscope
          go build -o ../vettool .
      - uses: reviewdog/action-setup@v1
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -reporter=github-pr-review
