name: reviewdog
on: [pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: build custom analyzer
        run: |
          go get -u github.com/gostaticanalysis/vetgen
          vetgen init _vettool
          cd _vettool
          vetgen add github.com/sapphi-red/possibleerrors/fordirection
          vetgen add github.com/sapphi-red/possibleerrors/avoidaccesslen
          vetgen add github.com/sapphi-red/possibleerrors/mutexscope
          go install .
      - uses: reviewdog/action-setup@v1
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go vet -vettool=$(which _vettool) . | reviewdog -f=govet -filter-mode=nofilter -reporter=github-pr-review -level=info
