name: reviewdog
on: [pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: fetch custom linter
        run: |
          curl -o linters.tar.gz -L https://github.com/sapphi-red/possibleerrors/releases/download/v0.1.14/possibleerrors_golang-ci-lint-plugin_0.1.14_linux_64bit.tar.gz
          tar -xzf linters.tar.gz
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          reviewdog_flags: -reporter=github-pr-review
